import React, { useEffect, useState } from 'react';
import { Sparkles, TrendingUp, AlertCircle, RefreshCw } from 'lucide-react';
import { useUser } from '@clerk/clerk-react';

export default function Insights() {
  const { user } = useUser();
  const [insights, setInsights] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  const fetchInsights = async () => {
    if (!user) return;
    setIsLoading(true);
    try {
      const res = await fetch(`http://localhost:5000/api/insights/${user.id}`);
      if (res.ok) {
        const data = await res.json();
        setInsights(data);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  const generateInsight = async () => {
    if (!user) return;
    setIsGenerating(true);
    try {
      const res = await fetch(`http://localhost:5000/api/insights/generate/${user.id}`, {
        method: 'POST'
      });
      if (res.ok) {
        fetchInsights();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    fetchInsights();
  }, []);

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <header className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-4xl font-extrabold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-white to-mint">
            AI Sustainability Insights
          </h1>
          <p className="text-mint">Personalized analysis generated by Gemini based on your recent activity.</p>
        </div>
        <button 
          onClick={generateInsight}
          disabled={isGenerating}
          className="flex items-center gap-2 bg-white/5 border border-white/10 hover:bg-white/10 text-white px-4 py-2 rounded-lg transition-all disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${isGenerating ? 'animate-spin' : ''}`} />
          {isGenerating ? 'Analyzing...' : 'Generate New Insight'}
        </button>
      </header>

      {isLoading ? (
        <div className="text-center text-mint py-10">Loading insights...</div>
      ) : insights.length === 0 ? (
        <div className="glass-panel p-8 text-center text-mint">
          No insights generated yet. Log some activities and generate your first insight!
        </div>
      ) : (
        <div className="space-y-6">
          {insights.map((insight) => (
            <div key={insight._id} className="glass-panel p-8 relative overflow-hidden group hover:border-accent-green/30 transition-all">
              <div className="absolute top-0 right-0 w-32 h-32 bg-accent-lime opacity-5 rounded-full blur-2xl group-hover:opacity-10 transition-opacity"></div>
              
              <div className="flex items-start gap-4">
                <div className="p-3 bg-accent-green/20 rounded-xl mt-1">
                  <Sparkles className="w-6 h-6 text-accent-green" />
                </div>
                
                <div className="flex-1 space-y-4">
                  <div>
                    <h3 className="text-lg font-bold text-white flex items-center gap-2">
                      <TrendingUp className="w-4 h-4 text-mint" /> 
                      Trend Analysis
                    </h3>
                    <p className="text-mint leading-relaxed mt-1">{insight.trendSummary}</p>
                  </div>
                  
                  <div className="p-4 bg-forest-dark/40 rounded-xl border border-white/5 relative">
                    <span className="absolute -top-3 left-4 bg-forest-dark px-2 text-xs font-bold text-accent-lime uppercase tracking-wider">
                      Eco Analogy
                    </span>
                    <p className="text-white font-medium italic">"{insight.geminiAnalogy}"</p>
                  </div>
                  
                  <div className="flex items-start gap-2 pt-2">
                    <AlertCircle className="w-5 h-5 text-accent-green mt-0.5" />
                    <div>
                      <span className="text-sm font-semibold text-white">Actionable Tip: </span>
                      <span className="text-sm text-mint">{insight.actionableTip}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
